{% set name = "dash-pydantic-form" %}
{% set name_utils = "dash-pydantic-utils" %}
{% set version = "0.14.1" %}
{% set python_min = "3.10" %}

package:
  name: dash-pydantic-form-and-utils
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dash_pydantic_form-{{ version }}.tar.gz
    sha256: fb6af5b84c245c8ff534c6381bca5e4d3a8f58f67add58266f1a2559f45761bd
  - url: https://pypi.org/packages/source/{{ name_utils[0] }}/{{ name_utils }}/dash_pydantic_utils-{{ version }}.tar.gz
    sha256: 79d6d36898167e7537c521a251dc32a99103b4bc2d4ebbf9d96fab7833c7be1b

build:
  number: 1

outputs:

  - name: {{ name }}
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}.*
        - setuptools >=67
        - setuptools-scm >=7.1
        - pip
      run:
        - python >={{ python_min }},<3.13
        - dash >=2.16
        - dash-mantine-components >=0.14.6,<0.16
        - dash-iconify
        - dash-ag-grid >=31
        - pydantic ==2.*
        - fsspec
        - {{ name_utils }} =={{ version }}
        # For some reason the below is not picked up from Dash's deps
        - Werkzeug <3.1

    test:
      imports:
        - dash_pydantic_form
      commands:
        - pip check
      requires:
        - python ={{ python_min }}
        - pip

  - name: {{ name_utils }}
    build:
      noarch: python
      script: pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python {{ python_min }}.*
        - setuptools >=67
        - setuptools-scm >=7.1
        - pip
      run:
        - python >={{ python_min }},<3.13
        - pydantic ==2.*

    test:
      imports:
        - dash_pydantic_utils
      commands:
        - pip check
      requires:
        - python ={{ python_min }}
        - pip

about:
  home: https://pydf-docs.onrender.com
  summary: Create Dash forms from pydantic objects
  dev_url: https://github.com/RenaudLN/dash-pydantic-form
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RenaudLN
