{% set name = "dash-pydantic-form" %}
{% set name_utils = "dash-pydantic-utils" %}
{% set version = "0.16.0" %}
{% set python_min = "3.10" %}

package:
  name: dash-pydantic-form-and-utils
  version: {{ version }}

source:
  - folder: form
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dash_pydantic_form-{{ version }}.tar.gz
    sha256: 5faeedbbf2c8d21dfc7e21f41f2505136333fc84470533a76773962f55fb952c
  - folder: utils
    url: https://pypi.org/packages/source/{{ name_utils[0] }}/{{ name_utils }}/dash_pydantic_utils-{{ version }}.tar.gz
    sha256: 0d74e8bb4cbe6b60099e9b28fa59cf27363e861db3df6fa85a582fe928844492

build:
  noarch: python
  number: 0

outputs:

  - name: {{ name_utils }}
    build:
      noarch: python
      script: cd utils && pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - python {{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >={{ python_min }},<3.14
        - pydantic ==2.*

    test:
      imports:
        - dash_pydantic_utils
      commands:
        - pip check
      requires:
        - python ={{ python_min }}
        - pip

  - name: {{ name }}
    build:
      noarch: python
      script: cd form && pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - python {{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >={{ python_min }},<3.14
        - dash >=2.16,<4
        - dash-mantine-components >=0.14.6,<1.2
        - dash-iconify
        - dash-ag-grid >=31
        - pydantic ==2.*
        - fsspec
        - {{ name_utils }} =={{ version }}
        # For some reason the below is not picked up from Dash's deps
        - Werkzeug <3.1

    test:
      imports:
        - dash_pydantic_form
      commands:
        - pip check
      requires:
        - python ={{ python_min }}
        - pip

about:
  home: https://pydf-docs.onrender.com
  summary: Create Dash forms from pydantic objects
  dev_url: https://github.com/RenaudLN/dash-pydantic-form
  license: MIT
  license_file: utils/LICENSE

extra:
  feedstock-name: {{ name }}
  recipe-maintainers:
    - RenaudLN
