{% set name = "dash-pydantic-form" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_pydantic_form-{{ version }}.tar.gz
  sha256: dc0c10ea5baeafb430cf90a7749f6c1079ab42105d4fb1b332243f14cb7d0ebb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - setuptools >=67
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.10,<3.13
    - dash
    - dash-mantine-components >=0.14
    - dash-iconify
    - dash-ag-grid
    - pandas
    - pydantic ==2.*

test:
  imports:
    - dash_pydantic_form
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pydf-docs.onrender.com
  summary: Create Dash forms from pydantic objects
  dev_url: https://github.com/RenaudLN/dash-pydantic-form
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RenaudLN
