{% set name = "dash-pydantic-form" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_pydantic_form-{{ version }}.tar.gz
  sha256: 5e2afb67524421358283cb292d1523edbb73c00e3dc1bc87ecfd914069ff94ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - setuptools >=67
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.10,<3.13
    - dash >=2.16
    - dash-mantine-components >=0.14.5
    - dash-iconify
    - dash-ag-grid >=31
    - pandas
    - pydantic ==2.*

test:
  imports:
    - dash_pydantic_form
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pydf-docs.onrender.com
  summary: Create Dash forms from pydantic objects
  dev_url: https://github.com/RenaudLN/dash-pydantic-form
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RenaudLN
